### ISSUE TITLE
Upload templating-maven-plugin:1.0.5 to central M2 repo

### ISSUE THREAD

**Issue by pfoermer** [wavesoftware/templating-maven-plugin-copy#1]
Hi,

would it be possible to upload the templating-maven-plugin:1.0.5 to central M2 repo? Currently the latest version in the central M2 repo is 1.0-alpha-3.

By the way: Thank you very much for this nice plugin! Solved a lot of work for me and simplified the understanding instead of using the the maven-build-helper-pluign.

Best regards,
Philipp

**Comment by cardil** [comment]
I'm not the original author of this plugin. I've converted the repository from old code from SVN in codehaus.org (which is closed right now)

I must contact them (@batmat, @stephenc) to ask if they still develop this one and if not I can publish to M2 under my own groupId: `pl.wavesoftware`.

If they still develop this I can give them pull request with my changes but for now I can't find other repo :-(

**Comment by cardil** [comment]
Plugin is still in development by MojoHous now. I've created a PR with my changes here: https://github.com/mojohaus/templating-maven-plugin/pull/1

**Comment by khmarbaise** [comment]
I will working on a release but it will be named 1.0.0 and not 1.0.5....

**Comment by cardil** [comment]
Closing this issue and I will delete this repository in couple of days since my changes want into main mojohaus repo: mojohaus/templating-maven-plugin#1

**Comment by pfoermer** [comment]
Ok.
Thank you for your support and effort!

**Comment by cardil** [comment]
This should be addressed with https://github.com/mojohaus/templating-maven-plugin/issues/6
